# Site settings
title: the little things
#email: your-email@domain.com
description: "The happy places discovered during Joey Mink's DevOps hackery."
baseurl: ""
url: "http://walknwind.github.io"
twitter_username: joeymink
github_username:  walknwind

# Build settings
markdown: kramdown
permalink: pretty
